title = "Lamoni Historical Association"
languageCode = "en-us"
baseURL = "/"
theme = "lha2"


disableKinds = ["taxonomyTerm","RSS"]


[permalinks]
exhibits = "/exhibits/:slug/"
events = "/events/:slug/"
stories = "/stories/:slug/"
pages = "/pages/:slug/"


[taxonomies]
person = "people"
place = "places"
theme = "themes"
year = "years"


[outputs]
home = ["HTML","JSON"]
section = ["HTML"]
page = ["HTML"]