[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Untold Lamoni Stories"
url = "/untold-lamoni-stories/"
weight = 2

[[main]]
name = "Lamoni Sesquicentennial 2029"
url = "/sesquicentennial-2029/"
weight = 3

[[main]]
name = "Book of Mormon Bicentennial 2030"
url = "/bicentennial-bom-2030/"
weight = 4

[[main]]
name = "Projects"
url = "/pages/projects/"
weight = 5

[[main]]
name = "About Us"
url = "/pages/about/"
weight = 6

[[footer]]
name = "Research"
url = "/pages/research/"
weight = 1

[[footer]]
name = "Visit"
url = "/pages/visit/"
weight = 2

[[footer]]
name = "Contact"
url = "/pages/contact/"
weight = 3

[[footer]]
name = "Donate"
url = "/pages/donate/"
weight = 4

