

[[main]]
name = "Untold Lamoni Stories"
url = "/untold-lamoni-stories/"
weight = 1

[[main]]
name = "Lamoni Sesquicentennial"
url = "/sesquicentennial-2029/"
weight = 2

[[main]]
name = "BOM Bicentennial"
url = "/bicentennial-bom-2030/"
weight = 3

[[main]]
name = "Projects"
url = "/projects/"
weight = 4

[[main]]
name = "About Us"
url = "/about/"
weight = 5

[[footer]]
name = "Research"
url = "/pages/research/"
weight = 1

[[footer]]
name = "Visit"
url = "/pages/visit/"
weight = 2

[[footer]]
name = "Contact"
url = "/pages/contact/"
weight = 3

[[footer]]
name = "Donate"
url = "/pages/donate/"
weight = 4

