[brand]
name = "Lamoni Historical Association"
short = "LHA"
primary = "#8B2E2C"
primaryDark = "#6E1E1C"
amber = "#F9C542"
amberDark = "#C26B1D"
useLogo = true
logoPath = "/images/logo.png"
logoAlt = "Lamoni Historical Association Logo"


[home]
showFeaturedExhibits = true
showFeaturedEvents = true
showFeaturedStories = true
showDonateCta = true
showRegisterCta = true
registerUrl = "/pages/untold-lamoni-stories/#register"
donateUrl = "/pages/donate/"