[brand]
name = "Lamoni Historical Association"
short = "LHA"
primary = "#8B2E2C"
primaryDark = "#6E1E1C"
amber = "#F9C542"
amberDark = "#C26B1D"
useLogo = true
logoPath = "/images/logo.svg"
logoAlt = "Lamoni Historical Association"


[home]
showFeaturedExhibits = true
showFeaturedEvents = true
showFeaturedStories = true
showDonateCta = true
showRegisterCta = true
registerUrl = "https://www.convergepay.com/hosted-payments?ssl_txn_auth_token=4jYHLRh9ThWl%2BXzBgg%2BxRAAAAZnu5kiW"
donateUrl = "https://www.convergepay.com/hosted-payments?ssl_txn_auth_token=4jYHLRh9ThWl%2BXzBgg%2BxRAAAAZnu5kiW"
ulsUrl = "/content/untold-lamoni-stories/_index"
