baseURL = "https://lamonihistoricalassociation.org"
languageCode = "en-us"
title = "Lamoni Historical Association"
theme = "lha"
pagerSize = 10
canonifyURLs = true
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xhtml = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

[permalinks]
stories = "/stories/:slug/"

[menu]
  [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 5

  [[menu.main]]
  name = "Projects"
  url  = "/projects/"
  weight = 10

  [[menu.main]]
  name = "Untold Stories"
  url  = "/untold-lamoni-stories/"
  weight = 20

  [[menu.main]]
  name = "Sesquicentennial 2029"
  url  = "/sesquicentennial-2029/"
  weight = 30

  [[menu.main]]
  name = "BOM Bicentennial 2030"
  url  = "/bicentennial-bom-2030/"
  weight = 40

  [[menu.main]]
  name = "Register"
  url  = "/register/"
  weight = 50

  [[menu.main]]
  name = "Donate"
  url  = "/donate/"
  weight = 60
